AZP: test log

diff --git a/buildlib/azure-pipelines-pr.yml b/buildlib/azure-pipelines-pr.yml
--- a/buildlib/azure-pipelines-pr.yml
+++ b/buildlib/azure-pipelines-pr.yml
@@ -154,6 +154,19 @@ stages:
               fi
             displayName: Configure source and build RPM
 
+  - stage: Logging
+    jobs:
+      - job: test log
+        displayName: test log
+        steps:
+          - bash: |
+              #!/bin/bash
+              echo "##vso[task.logissue type=warning]Found something that could be a problem"
+          - bash: |
+              #!/bin/bash
+              echo "##vso[task.logissue type=error]Something went very wrong."
+              exit 1
+
   - stage: Tests
     dependsOn: [Codestyle]
     jobs:
